spring.application.name=checkout-service
server.port=9007
cart.service.url=${CART_SERVICE_URL:http://cart-service}
order.service.url=${ORDER_SERVICE_URL:http://order-service}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:9004/eureka}
management.endpoints.web.exposure.include=health,info,prometheus
