spring.application.name=product-service
spring.data.mongodb.auto-index-creation=true
server.port=9000
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/product-service}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:9004/eureka}
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
