spring.application.name=cart-service
server.port=9006
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/cart-service}
product.service.url=${PRODUCT_SERVICE_URL:http://product-service}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:9004/eureka}
management.endpoints.web.exposure.include=health,info,prometheus
